workflows:
  android-build:
    name: Android Build
    max_build_duration: 45
    environment:
      node: latest
      vars:
        ANDROID_HOME: $ANDROID_HOME
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android APK
        script: npx eas build --platform android --profile preview --non-interactive
    artifacts:
      - build/**/*.apk
      - build/**/*.aab
