"""PDF report service — รวมผลดวงเป็นไฟล์ PDF ภาษาไทยสวยๆ.

ใช้ reportlab + Sarabun (OFL, bundled in assets/fonts) เป็นฟอนต์หลัก
รองรับทั้ง Windows/Linux/macOS (CI-safe). ถ้า bundle หาย ลองหา system font
ก่อนแล้วค่อย fallback เป็น Helvetica (ข้อความไทยจะไม่ render — test จะจับตอนนั้น)
ข้อความดึงจาก src.services.templates (โหรพูดจริง th/en) — ไม่แต่งใหม่ที่นี่
"""
from __future__ import annotations

import os
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
)

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
_BUNDLED_DIR = os.path.join(_REPO_ROOT, "assets", "fonts")

_SYSTEM_FONT_DIRS = [
    r"C:\Windows\Fonts",
    "/usr/share/fonts/truetype/ttf-sarabun",
    "/usr/share/fonts/truetype/thai",
    "/usr/share/fonts",
    "/System/Library/Fonts",
    "/Library/Fonts",
]


def _find_font(names: list[str]) -> str | None:
    for d in [ _BUNDLED_DIR ] + _SYSTEM_FONT_DIRS:
        if not os.path.isdir(d):
            continue
        for n in names:
            p = os.path.join(d, n)
            if os.path.exists(p):
                return p
    return None


_regular_path = _find_font(["Sarabun-Regular.ttf", "tahoma.ttf", "loma.ttf"])
_bold_path = _find_font(["Sarabun-Bold.ttf", "tahomabd.ttf", "lomabd.ttf"])

if _regular_path:
    pdfmetrics.registerFont(TTFont("Thai", _regular_path))
else:  # last resort — Thai text will not render, tests catch this on CI
    pdfmetrics.registerFont(TTFont("Thai", "Helvetica"))
    _regular_path = None

if _bold_path:
    pdfmetrics.registerFont(TTFont("Thai-Bold", _bold_path))
elif _regular_path:
    pdfmetrics.registerFont(TTFont("Thai-Bold", _regular_path))
else:
    pdfmetrics.registerFont(TTFont("Thai-Bold", "Helvetica"))

# ── palette (cosmic theme) ───────────────────────────────────────────
_BG_DARK = HexColor("#1a0b2e")
_ACCENT = HexColor("#ff9800")
_TEXT = HexColor("#2a2a3a")
_MUTED = HexColor("#777788")

# ── styles ───────────────────────────────────────────────────────────
_S_TITLE = ParagraphStyle("title", fontName="Thai-Bold", fontSize=22,
                          textColor=_BG_DARK, leading=30)
_S_SUB = ParagraphStyle("sub", fontName="Thai", fontSize=11,
                        textColor=_MUTED, leading=16)
_S_H2 = ParagraphStyle("h2", fontName="Thai-Bold", fontSize=14,
                       textColor=_ACCENT, leading=20, spaceBefore=10)
_S_BODY = ParagraphStyle("body", fontName="Thai", fontSize=10.5,
                         textColor=_TEXT, leading=17)


def thai_font_available() -> bool:
    """True when a real Thai-capable TTF was registered."""
    return _regular_path is not None


def render_report_pdf(
    sections: list[dict],
    out_path: str,
    person_name: str = "",
    lang: str = "th",
) -> str:
    """sections: [{"title": str, "lines": [str, ...]}, ...]  (already humanized text)"""
    doc = SimpleDocTemplate(
        out_path, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm,
        topMargin=16 * mm, bottomMargin=16 * mm,
        title="Astral Report", author="Astral App",
    )
    story: list = []

    title = "รายงานดวงชะตา" if lang == "th" else "Astrology Report"
    if person_name:
        title += f" — {person_name}"
    story.append(Paragraph(title, _S_TITLE))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        datetime.now().strftime("%d/%m/%Y") +
        (" · จัดทำโดย Astral" if lang == "th" else " · Generated by Astral"),
        _S_SUB,
    ))
    rule = Table([[""]], colWidths=[174 * mm], rowHeights=[0.6 * mm])
    rule.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), _ACCENT),
    ]))
    story.append(rule)
    story.append(Spacer(1, 12))

    for sec in sections:
        story.append(Paragraph(sec["title"], _S_H2))
        for line in sec["lines"]:
            story.append(Paragraph(line, _S_BODY))
            story.append(Spacer(1, 2))
        story.append(Spacer(1, 8))

    doc.build(story)
    return out_path
